ansible_mitogen: Make injected __main__ on target more identifiable/greppable
This is intended as a maker's mark, so it sticks out in a traceback and makes
debugging easier. The injection has been moved to ansible_mitogen.runner
because it is already the place we import ansible.module_utils.basic and
perform other manipulations.

Before
```python
>>> __main__.foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module '__main__' has no attribute 'foo'
```

After
```python
>>> __main__.foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ansible_mitogen.injected.i_cant_believe_its_not__main__' has no attribute 'foo'
```