mitogen: Fix TypeError in is_stdlib_name(<implicit namespace package>)
A PEP 420 implicit namesapce package will have the value None for
module.spec.originandmodule.file. This causes a TypeError when calling
os.path.abspath() in mitogen.master.is_stdlib_name()`, which results in
failing to serve any module that imports that namespace module.

Traceback (most recent call last):
  ...
  File ".../site-packages/mitogen/master.py", line 140, in is_stdlib_name
    modpath = os.path.abspath(getattr(module, '__file__', ''))
  File "/usr/lib/python3.10/posixpath.py", line 378, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType