tests: FIx race condition in leaked file descriptor check
On the occasions that tests.connection_test.FetchFileTest reported
leaked file descriptors. However the error printed did not show a
mismatch, e.g.

AssertionError: test_success (tests.connection_test.FetchFileTest)
leaked FDs. Count before: 4, after: 4

I believe this is due to Time of Check to Time of Use (TOCTOU) bug.
Following this change the discovered mismatch is more accurately
reported

```
======================================================================
FAIL: test_success (tests.connection_test.FetchFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/alex/src/mitogen/tests/ansible/tests/connection_test.py",
line 73, in tearDown
    super(ConnectionMixin, self).tearDown()
  File "/home/alex/src/mitogen/tests/testlib.py", line 382, in tearDown
    self._teardown_check_fds()
File "/home/alex/src/mitogen/tests/testlib.py", line 353, in
_teardown_check_fds
    self, self._fd_count_before, fd_count_after,
AssertionError: test_success (tests.connection_test.FetchFileTest)
leaked FDs. Count before: 6, after: 7
```

refs #761